# Breakfast

## French Toast

**Ingredients**

1. Two slices of bread 
2. One egg
3. A couple of tablespoons of milk
4. Sugar to taste
5. A drop of vanilla extract
6. Powdered sugar for dressing (optional)

**Steps**

1. Whisk the egg with milk and sugar until the sugar is dissolved. 
2. Add a drop of vanilla extract and mix it well.
3. Pour the mix into a vast and shallow bowl or plate.
4. Soak the bread slice on both sides.
5. Shallow fry the soaked bread in butter or oil. 

## Vegetable Namkeen (salted) Jave (Vermicelli Upma) 

**Ingredients**

1. Roasted vermicelli (1 cup)
2. Water (2 cups; twice as much as vermicelli)
3. Finely chopped onions and tomato
4. Finely chopped vegetables (carrots and/or peas and/or corn)
5. Cashews
6. Oil, cumin seeds, curry leaves, salt, and green chillies 

**Steps**

1. Heat oil in a deep pan
2. Add cumin seeds, curry leaves, and green chillies
3. Caramelize some onions
4. Add vegetables and sauté them at medium heat
5. Add tomatoes and cashews
6. Once the vegetables are cooked and tender, add vermicelli with twice as much water as vermicelli.
7. Cover and simmer for 10 minutes or until vermicelli is cooked.
