# Roasts

## Oven Roasted Tandoori Chicken

Marinate chicken in Shan tandoori chicken masala, food color, curd/lemon juice, and ginger-garlic paste for at least 2 hrs. 

**Baking Steps**

1. Preheat oven to **360 degrees**.
2. Place marinated chicken on the baking rack so that the liquids can drip and get collected in the tray.
3. **Cover** with foil and cook for **45 minutes**. 
4. **Uncover**, baste with fluids, spray oil, or dribble oil on all the pieces, and bake uncovered for **15 minutes.**

## Oven Roasted Salmon

**Ingredients and Marinade**

1. Fresh Atlantic salmon fillet.
2. Grill mates roasted garlic & herb seasoning [https://www.mccormick.com/grill-mates/flavors/seasoning-blends/grill-mates-roasted-garlic-herb-seasoning](https://www.mccormick.com/grill-mates/flavors/seasoning-blends/grill-mates-roasted-garlic-herb-seasoning)) or another seasoning of your choice.
3. Salt and pepper to taste.
4. Butter.
5. Marinate fish fillets on both sides with a mix of seasoning, salt, and pepper, and baste with butter.

**Baking Steps**

1. Preheat the oven to 375 degrees.
2. Bake at 375 degrees for 12 minutes, then broil at low to medium (~ 350 degrees) for 12 - 15 minutes. 


## Oven Roasted Mustard Salmon

**Ingredients and Marinade**

1. Fresh Atlantic salmon fillet.
2. Whole/Dijon mustard sauce. 
3. Chopped garlic. 
4. Chopped parsley.
5. Lemon juice.
6. Avocado oil.
7. Salt and pepper.

**Baking Steps**

1. Preheat the oven to 375 degrees.
2. Bake at 375 degrees for 20 minutes. 